management/wine/models.py
# -*- coding:utf-8 -*-
import hashlib
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app, request
from flask_security import Security, UserMixin, login_required
from mongoengine import *
from wine import db, login_manager

class User(db.Document):
    email = StringField(max_length=64)
    username = StringField(max_length=64)
    password = StringField(max_length=256)
    created_at = DateTimeField(default=datetime.utcnow)

    def verify_password(self, password):
        return check_password_hash(self.password, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True

    def generate_reset_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id})

    def reset_password(self, token, new_password):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('reset') != self.id:
            return False
        self.password = new_password
        db.session.add(self)
        db.session.commit()
        return True

    def generate_email_change_token(self, new_email, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'change_email': self.id, 'new_email': new_email})

    def change_email(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('change_email') != self.id:
            return False
        new_email = data.get('new_email')
        if new_email is None:
            return False
        if self.query.filter_by(email=new_email).first() is not None:
            return False
        self.email = new_email
        db.session.add(self)
        db.session.commit()
        return True

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
        db.session.commit()

    # TypeError: ObjectId('552f41e56a85f00dd043406b') is not JSON serializable
    def get_id(self):
        return str(self.id)

    # Flask-Login integration
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def __repr__(self):
        if self.username is not None:
            return u'{name}'.format(name=self.username)
        return u'{name}'.format(name=self.username)

@login_manager.user_loader
def load_user(user_id):
    return User.objects(id=user_id).first()

class Store(db.Document):
    name = StringField(max_length=256)
    city = StringField(max_length=256)
    sys_store_id = StringField(max_length=64)
    created_at = DateTimeField(default=datetime.utcnow)
    updated_at = DateTimeField(default=datetime.utcnow)

management/wine/main/forms.py
# -*- coding:utf-8 -*-
from flask import request
from flask_wtf import Form
from wtforms.fields.html5 import TelField
from wtforms import StringField, TextAreaField, BooleanField, SelectField, RadioField, FieldList, FormField, SubmitField
from wtforms.validators import Required, Length, Email, Regexp
from wtforms import ValidationError
from ..models import User

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class CustomerForm(Form):
    name = StringField('姓名', validators=[Length(0, 64)])

management/wine/__init__.py
from flask import Flask
from flask_mail import Mail
from flask_admin import Admin
from flask_moment import Moment
from flask_bootstrap import WebCDN
from flask_bootstrap import Bootstrap
from flask_login import LoginManager, current_user
from flask_mongoengine import MongoEngine

app = Flask(__name__)
app.config.from_object('config')

mail = Mail(app)
moment = Moment(app)
bootstrap = Bootstrap(app)
login_manager = LoginManager(app)
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

db = MongoEngine(app)

admin = Admin(app, name='ADMIN', template_mode='bootstrap3')
from .admin import *

from main import main
from auth import auth

app.register_blueprint(main)
app.register_blueprint(auth, url_prefix='/auth')

# Maybe better for China
app.extensions['bootstrap']['cdns']['jquery'] = WebCDN('//cdn.bootcss.com/jquery/2.1.4/')
app.extensions['bootstrap']['cdns']['bootstrap'] = WebCDN('//cdn.bootcss.com/bootstrap/3.3.5/')

management/wine/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

views.register_request(main)

management/wine/main/views.py
# -*- coding:utf-8 -*-
from flask import render_template, redirect, url_for, abort, flash, request,\
    current_app, g, make_response, send_file
from flask_login import login_required, current_user
from . import main
from .. import db
from ..models import User
from wine_excel import WineExcel
from inventory_excel import InventoryExcel

import threading

import os, time, datetime, calendar
import simplejson

def register_request(app):
    @app.before_request
    def register_g():
        # g.status_to_title=['A', 'B', 'C', 'D', 'E']
        # g.status_to_title_dict={None: '', 0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E'}
        pass

def export_inventory_excel(start_date, end_date, category):
    inventoryExcel = InventoryExcel(start_date, end_date, category)

def export_wine_excel(category):
    wineExcel = WineExcel(category)

@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('main.html')

@main.route('/export_inventory', methods=['POST'])
@login_required
def export_inventory():
    if request.method == 'POST':
        start_date = request.args.get('start_date', '')
        end_date = request.args.get('end_date', '')
        category = request.args.get('category', '')

        start_day = datetime.datetime.strptime(start_date,'%Y-%m-%d')
        end_day = datetime.datetime.strptime(end_date,'%Y-%m-%d')
        days_count = (end_day-start_day).days

        if days_count > 31:
            data = { "msg":"Please don't select more than 31 days", "code":"0001" }
        else:
            threads = []
            thread = threading.Thread(target=export_inventory_excel,args=(start_date, end_date, category))
            threads.append(thread)
            for t in threads:
                t.setDaemon(True)
                t.start()

            data = { "msg":"Executed", "code":"0000" }
        
        return simplejson.dumps(data)

@main.route('/export_wine', methods=['POST'])
@login_required
def export_wine():
    if request.method == 'POST':

        category = request.args.get('category', '')

        threads = []
        thread = threading.Thread(target=export_wine_excel,args=(category,))
        threads.append(thread)
        for t in threads:
            t.setDaemon(True)
            t.start()

        data = { "msg":"Executed", "code":"0000" }
        
        return simplejson.dumps(data)

@main.route('/get_excel_progress', methods=['GET'])
@login_required
def get_excel_progress():
    type = request.args.get('type', '')

    if type == 'inventory':
        file_name = 'inventory.log'
    elif type == 'wine':
        file_name = 'wine.log'

    if os.path.exists(file_name):
        log_file = open(file_name)
        log_msg = log_file.readline()
        data = { "msg":log_msg, "code":"0000" }
    else:
        data = { "msg":'Generating...', "code":"0000" }
    
    return simplejson.dumps(data)

@main.route('/download_excel')
@login_required
def download_excel():

    type = request.args.get('type', '')
    category = request.args.get('category', '')

    if type == 'wine':
        file_name = 'product_'
    else:
        file_name = 'inventory_'

    file_name = file_name + category + '.csv'
    file_path = os.getcwd() + '/' + file_name

    print file_path

    response = make_response(send_file(file_path))
    response.headers["Content-Disposition"] = "attachment; filename=%s;" % file_name
    return response

management/wine/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
            上一页
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
            下一页
        </a>
    </li>
</ul>
{% endmacro %}

management/wine/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Management{% endblock %}

{% block head %}
{{ super() }}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<!-- <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon"> -->
<link rel="apple-touch-icon" href="http://7xkiee.com2.z0.glb.qiniucdn.com/180%20-%20iPhone%206%20Plus-1.png" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container header_height">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.index') }}"><img alt="logo" src="{{ url_for('static', filename='img/bt_logo.png') }}"></a>
        </div>
        <!-- <div class="navbar-collapse collapse"> -->
            <ul class="nav navbar-nav fr">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown">
                        {{ current_user.username }}<!-- <b class="caret"> --></b>
                    </a>
                    <!-- <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul> -->
                </li>
                {% endif %}
            </ul>
        <!-- </div> -->
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

{{ moment.include_moment(local_js='http://7u2mcc.com1.z0.glb.clouddn.com/moment-with-locales.min.js') }}
<script>
    $(document).ready(function() {
      $('.js-activated').dropdownHover();
    });
</script>
<script src="{{ url_for('static', filename='js/twitter-bootstrap-hover-dropdown.min.js') }}"></script>

{% endblock %}

management/wine/templates/main.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Management{% endblock %}

{% block head %}
{{ super() }}
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{{ url_for('static', filename='css/calendar.css') }}">
{% endblock %}

{% block page_content %}

<div class="header clearfix">
    <h3 class="text-muted">Export Inventory Data</h3>
</div>

<div class="select">
  <select name="select" id="category_select_inventory" class="form-control">
    <option value="red_wine">Rött vin</option>
    <option value="white_wine">Vitt vin</option>
    <option value="beer">Öl</option>
    <option value="whisky">Whisky</option>
  </select>
</div>

<div class="select_date">
  <div class="form-group">
    <input type="text" class="form-control" id="start_date" placeholder="Start Date">
  </div>
  <div id="start_calendar"></div>
</div>
<div class="select_date">
    <input type="text" class="form-control" id="end_date" placeholder="End Date">
  <div id="end_calendar"></div>
</div>

<a id="export_inventory_btn" class="btn btn-success" type="button">Export</a>

<p>&nbsp;</p>

<div class="header clearfix">
    <h3 class="text-muted">Export Product Data</h3>
</div>

<div class="select">
  <select name="select" id="category_select_wine" class="form-control">
    <option value="red_wine">Rött vin</option>
    <option value="white_wine">Vitt vin</option>
    <option value="beer">Öl</option>
    <option value="whisky">Whisky</option>
  </select>
</div>

<a id="export_wine_btn" class="btn btn-success" type="button">Export</a>

<script src="{{ url_for('static', filename='js/jquery.js') }}"></script> 
<script src="{{ url_for('static', filename='js/calendar.js') }}"></script>
<script src="{{ url_for('static', filename='js/time.js') }}"></script> 
<script type="text/javascript">
    var start_date = ""
    var end_date = ""
    $('#start_calendar').calendar({
      width: 320,
      height: 320,
      trigger: '#start_date',
      zIndex: 999,
      format: 'yyyy-mm-dd',
        onSelected: function (view, date, data) {
            console.log('event: onSelected')
        },
        onClose: function (view, date, data) {
            console.log('event: onClose')
            console.log('view:' + view)
            console.log('date:' + date)
            console.log('data:' + (data || 'None'));
            start_date = formatDate(date, "yyyy-MM-dd")
        }
    });
    $('#end_calendar').calendar({
      width: 320,
      height: 320,
      trigger: '#end_date',
      zIndex: 999,
      format: 'yyyy-mm-dd',
        onSelected: function (view, date, data) {
            console.log('event: onSelected')
        },
        onClose: function (view, date, data) {
            console.log('event: onClose')
            console.log('view:' + view)
            console.log('date:' + date)
            console.log('data:' + (data || 'None'));
            end_date = formatDate(date, "yyyy-MM-dd")
        }
    });

    // 定时刷新最新的生成 excel 的进度
    var timer = new Object();

    var alreadyDownload = false

    function get_excel_progress(type, category) {
      $.ajax({
          type: "get",
          dataType: "json",
          url: "get_excel_progress?type="+type,
          complete: function (resp) {
            var data = $.parseJSON(resp.responseText);
            console.log(data.msg);
            if (data.msg != "") {
              btnName = "export_" + type + "_btn" 
              document.getElementById(btnName).innerHTML = data.msg
              if (data.msg == "99%") {
                document.getElementById(btnName).innerHTML = "Generating..."
              }
              if (data.msg == "100%" && !alreadyDownload) {
                alreadyDownload = true
                clearInterval(timer);
                document.getElementById(btnName).innerHTML = "Finished"
                window.location.href="/download_excel?type="+type+"&category="+category;
                setTimeout("refreshPage()", 1000);
              }
            }
          },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
              console.log(XMLHttpRequest.status);
              console.log(XMLHttpRequest.readyState);
              console.log(textStatus);
            }
      });
    }
    $(function () {
      $("#export_inventory_btn").click(function () {
        if (start_date != "" && end_date != "") {
          var category = $('#category_select_inventory').val()
          $.ajax({
            type: "post",
            dataType: "json",
            url: "export_inventory?start_date="+start_date+"&end_date="+end_date+"&category="+category,
            complete: function (resp) {

              var data = $.parseJSON(resp.responseText);
              console.log(data.code);
              console.log(data.msg);

              if (data.code == '0000') {
                document.getElementById("export_inventory_btn").innerHTML = "Generating..."
                timer = window.setInterval(function(){ 
                  get_excel_progress("inventory", category);
                }, 1000);
              }else{
                alert(data.msg);
              }
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
              console.log(XMLHttpRequest.status);
              console.log(XMLHttpRequest.readyState);
              console.log(textStatus);
            }
          });
        }else{
          alert("Please select the date");
        }
      });

      $("#export_wine_btn").click(function () {
        var category = $('#category_select_wine').val()
        $.ajax({
          type: "post",
          dataType: "json",
          url: "export_wine?category="+category,
          complete: function (resp) {

            var data = $.parseJSON(resp.responseText);
            console.log(data.code);
            console.log(data.msg);

            if (data.code == '0000') {
              document.getElementById("export_wine_btn").innerHTML = "Generating..."
              timer = window.setInterval(function(){ 
                get_excel_progress("wine", category);
              }, 1000);
            }else{
              alert(data.msg);
            }
            
          },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            console.log(XMLHttpRequest.status);
            console.log(XMLHttpRequest.readyState);
            console.log(textStatus);
          }
        });
      });
    });

    function refreshPage() {
      window.location.reload(false); 
    }
</script>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}